-- ARTHUR MARQUES GOMES DA SILVA
-- TABELA ESPECIALIDADE
-- ATIVIDADE 01
-- TURMA JAVA 2

CREATE TABLE TBL_ESPECIALIDADE(
CD_ESPECIALIDADE NUMBER(8,0),
NM_ESPECIALIDADE VARCHAR2(60),
CONSTRAINT ESPECIALIDADE_PK PRIMARY KEY (CD_ESPECIALIDADE)
);

CREATE SEQUENCE TBL_ESPECIALIDADE_SEQ
  MINVALUE 1
  MAXVALUE 9999999999999999999
  START WITH 1
  INCREMENT BY 1;