-- ARTHUR MARQUES GOMES DA SILVA
-- TABELA MEDICAMENTO
-- ATIVIDADE 01
-- TURMA JAVA 2

CREATE TABLE TBL_MEDICAMENTO(
CD_MEDICAMENTO NUMBER(8,0),
NM_MEDICAMENTO VARCHAR2(60),
NM_DOSAGEM VARCHAR2(60),
CONSTRAINT MEDICAMENTO_PK PRIMARY KEY (CD_MEDICAMENTO)
);

CREATE SEQUENCE TBL_MEDICAMENTO_SEQ
  MINVALUE 1
  MAXVALUE 9999999999999999
  START WITH 1
  INCREMENT BY 1;