-- ARTHUR MARQUES GOMES DA SILVA
-- INSERT DAS ESPECIALIDADES
-- ATIVIDADE 01
-- TURMA JAVA 2

INSERT INTO TBL_ESPECIALIDADE
VALUES
(TBL_ESPECIALIDADE_SEQ.NEXTVAL,
'Cardiologia'
);

INSERT INTO TBL_ESPECIALIDADE
VALUES
(TBL_ESPECIALIDADE_SEQ.NEXTVAL,
'Endocrinologia'
);

INSERT INTO TBL_ESPECIALIDADE
VALUES
(TBL_ESPECIALIDADE_SEQ.NEXTVAL,
'Pediatria'
);

INSERT INTO TBL_ESPECIALIDADE
VALUES
(TBL_ESPECIALIDADE_SEQ.NEXTVAL,
'Neurologia'
);

INSERT INTO TBL_ESPECIALIDADE
VALUES
(TBL_ESPECIALIDADE_SEQ.NEXTVAL,
'Urologia'
);

INSERT INTO TBL_ESPECIALIDADE
VALUES
(TBL_ESPECIALIDADE_SEQ.NEXTVAL,
'Psiquiatria'
);

INSERT INTO TBL_ESPECIALIDADE
VALUES
(TBL_ESPECIALIDADE_SEQ.NEXTVAL,
'Anestesiologia'
);

INSERT INTO TBL_ESPECIALIDADE
VALUES
(TBL_ESPECIALIDADE_SEQ.NEXTVAL,
'Endoscopia'
);

INSERT INTO TBL_ESPECIALIDADE
VALUES
(TBL_ESPECIALIDADE_SEQ.NEXTVAL,
'Ginecologia'
);

INSERT INTO TBL_ESPECIALIDADE
VALUES
(TBL_ESPECIALIDADE_SEQ.NEXTVAL,
'Dermatologia'
);

INSERT INTO TBL_ESPECIALIDADE
VALUES
(TBL_ESPECIALIDADE_SEQ.NEXTVAL,
'Oftalmologia'
);

INSERT INTO TBL_ESPECIALIDADE
VALUES
(TBL_ESPECIALIDADE_SEQ.NEXTVAL,
'Ortopedia'
);