-- ARTHUR MARQUES GOMES DA SILVA
-- INSERT DOS MEDICAMENTOS
-- ATIVIDADE 01
-- TURMA JAVA 2

INSERT INTO TBL_MEDICAMENTO
VALUES
(TBL_MEDICAMENTO_SEQ.NEXTVAL,
'BROMETO DE IPRATRÓPIO',
'0,02MG'
);

INSERT INTO TBL_MEDICAMENTO
VALUES
(TBL_MEDICAMENTO_SEQ.NEXTVAL,
'DIPROPIONATO DE BECLOMETSONA',
'250MCG'
);

INSERT INTO TBL_MEDICAMENTO
VALUES
(TBL_MEDICAMENTO_SEQ.NEXTVAL,
'INSULINA HUMANA',
'100UI/ML'
);

INSERT INTO TBL_MEDICAMENTO
VALUES
(TBL_MEDICAMENTO_SEQ.NEXTVAL,
'SINVASTATINA',
'10MG'
);

INSERT INTO TBL_MEDICAMENTO
VALUES
(TBL_MEDICAMENTO_SEQ.NEXTVAL,
'ATENOLOL',
'25MG'
);

INSERT INTO TBL_MEDICAMENTO
VALUES
(TBL_MEDICAMENTO_SEQ.NEXTVAL,
'LOSARTANA POTÁSSICA',
'50MG'
);

INSERT INTO TBL_MEDICAMENTO
VALUES
(TBL_MEDICAMENTO_SEQ.NEXTVAL,
'DIPIRONA SÓDICA',
'50MG'
);

INSERT INTO TBL_MEDICAMENTO
VALUES
(TBL_MEDICAMENTO_SEQ.NEXTVAL,
'DIPIRONA SÓDICA',
'100ML'
);

INSERT INTO TBL_MEDICAMENTO
VALUES
(TBL_MEDICAMENTO_SEQ.NEXTVAL,
'DRAMIN',
'50MG'
);

INSERT INTO TBL_MEDICAMENTO
VALUES
(TBL_MEDICAMENTO_SEQ.NEXTVAL,
'DRAMIN',
'100MG'
);