-- ARTHUR MARQUES GOMES DA SILVA
-- TABELA PACIENTE
-- ATIVIDADE 01
-- TURMA JAVA 2

CREATE TABLE TBL_PACIENTE(
CD_PACIENTE NUMBER(8,0),
NM_PACIENTE VARCHAR2(60),
SEXO VARCHAR2(1),
CD_ENDERECO NUMBER(8,0),
CONSTRAINT PACIENTE_PK PRIMARY KEY (CD_PACIENTE),
CONSTRAINT ENDERECO_PACIENTE_FK FOREIGN KEY (CD_ENDERECO) REFERENCES TBL_ENDERECO(CD_ENDERECO)
);

ALTER TABLE TBL_PACIENTE
ADD CONSTRAINT TBL_PACIENTE_SEXO_CHECK
CHECK (SEXO IN('F','M'));

CREATE SEQUENCE TBL_PACIENTE_SEQ
  MINVALUE 1
  MAXVALUE 9999999999999999999
  START WITH 1
  INCREMENT BY 1;